import InhomogeneousDeformations.SourceLifts

/-!
# I106 R4 — `lem:source-isomorphism` (X0-X4)

Transcription: `eq:source` (manuscript lines 74-77): `A_β` is generated by even `b_u` and odd
`a` subject to `[b_u,b_v]=J_{uv}1`, `[b_u,a]=β_uκ`, `a²=½1`. `lem:source-isomorphism` (lines
108-125): mutually inverse even `R`-algebra maps `Φ:A_β→A_B`, `b_u↦B_u+β_uκa`,
`Ψ:A_B→A_β`, `B_u↦b_u-β_uκa`, fixing `a` and `R`.

**Route (b)**: `A_β` is realized concretely inside `AB n`, not via `FreeAlgebra`/`RingQuot`.
`b_u := B_u + β_u•κ•a` is defined as a specific element `bU n u : AB n`, and `eq:source`'s three
relations are proved as **theorems** about `bU`, never built into its definition (the
anti-circularity obligation, §S).
-/

namespace InhomogeneousDeformations
namespace Source

open scoped TensorProduct

/-! ## `B_u`, embedded into `A_B` -/

noncomputable def BuAB (n : ℕ) (u : Fin (2 * n)) : AB n := (1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n u)

theorem BuAB_mul (n : ℕ) (u v : Fin (2 * n)) :
    BuAB n u * BuAB n v = (1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n u * Bu0 n v) := by
  unfold BuAB
  have h := GradedTensorProduct.tmul_coe_mul_one_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (1 : RRing n) (⟨Bu0 n u, Bu0_mem_A0Grading_zero n u⟩ : A0Grading n 0) (Bu0 n v)
  simpa using h

/-! ## `β_u κ`, and `b_u := B_u + β_u κ a` -/

/-- `β_u`, embedded into `R` via the algebra map `Indexed.Pn n → RRing n` (automatic, since
`RRing n = CliffordAlgebra (Qzero n)` derives `Algebra (Indexed.Pn n) (RRing n)`), times `κ`. -/
noncomputable def betaKappa (n : ℕ) (u : Fin (2 * n)) : RRing n :=
  algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n u) * kappa n

noncomputable def betaKappaAB (n : ℕ) (u : Fin (2 * n)) : AB n :=
  (betaKappa n u) ᵍ⊗ₜ[ℚ] (1 : A0 n)

/-- `b_u := B_u + β_u κ a`, as a specific element of `AB n` (route (b), §3 of the scope). -/
noncomputable def bU (n : ℕ) (u : Fin (2 * n)) : AB n :=
  BuAB n u + betaKappaAB n u * aAB n

/-- The manuscript's own device: `c := κa`. -/
noncomputable def cAB (n : ℕ) : AB n := kappaAB n * aAB n

/-- `aκ = -κa`, rearranged from `A3_independence`. -/
theorem aAB_mul_kappaAB (n : ℕ) : aAB n * kappaAB n = -(kappaAB n * aAB n) := by
  have h := (A3_independence n).1
  rw [h, neg_neg]

/-- **X2, first fact**: `c² = 0`. `c*c = κ(aκ)a = κ(-κa)a = -(κ²)(a²) = 0`. -/
theorem cAB_sq (n : ℕ) : cAB n * cAB n = 0 := by
  unfold cAB
  have e1 : kappaAB n * aAB n * (kappaAB n * aAB n)
      = kappaAB n * (aAB n * kappaAB n) * aAB n := by noncomm_ring
  rw [e1, aAB_mul_kappaAB]
  have e2 : kappaAB n * (-(kappaAB n * aAB n)) * aAB n
      = -((kappaAB n * kappaAB n) * (aAB n * aAB n)) := by noncomm_ring
  rw [e2]
  have hk : kappaAB n * kappaAB n = 0 := by
    unfold kappaAB
    rw [GradedTensorProduct.tmul_zero_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
      (kappa n) (⟨1, SetLike.one_mem_graded (A0Grading n)⟩ : A0Grading n 0)
      (⟨kappa n, kappa_mem_RGradingQ_one n⟩ : RGradingQ n 1) (1 : A0 n)]
    rw [kappa_sq, mul_one]
    simp [GradedTensorProduct.tmul]
  rw [hk, zero_mul, neg_zero]

theorem aA0_sq (n : ℕ) : aA0 n * aA0 n = (1 / 2 : ℚ) • (1 : A0 n) := by
  unfold aA0
  rw [GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := WGrading n) (ℬ := CGrading)
    (1 : Module.End ℚ (WPoly n)) (⟨Source.a, Source.a_odd⟩ : CGrading 1)
    (⟨1, trivial⟩ : WGrading n 0) (Source.a : C)]
  rw [one_mul, Source.a_sq]
  show (1 : Module.End ℚ (WPoly n)) ᵍ⊗ₜ[ℚ] ((1 / 2 : ℚ) • (1 : C)) = (1 / 2 : ℚ) • (1 : A0 n)
  unfold GradedTensorProduct.tmul
  rw [TensorProduct.tmul_smul, map_smul, ← GradedTensorProduct.tmul, GradedTensorProduct.tmul,
    ← Algebra.TensorProduct.one_def, GradedTensorProduct.of_one]

/-- `a² = 1/2 • 1` embedded into `AB n`. -/
theorem aAB_sq (n : ℕ) : aAB n * aAB n = (1 / 2 : ℚ) • (1 : AB n) := by
  unfold aAB
  rw [GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (1 : RRing n) (⟨aA0 n, aA0_mem_A0Grading_one n⟩ : A0Grading n 1)
    (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (aA0 n)]
  rw [mul_one, aA0_sq]
  show (1 : RRing n) ᵍ⊗ₜ[ℚ] ((1 / 2 : ℚ) • (1 : A0 n)) = (1 / 2 : ℚ) • (1 : AB n)
  unfold GradedTensorProduct.tmul
  rw [TensorProduct.tmul_smul, map_smul, ← GradedTensorProduct.tmul, GradedTensorProduct.tmul,
    ← Algebra.TensorProduct.one_def, GradedTensorProduct.of_one]

/-- **X2, second fact**: `[c,a] = κ` (plain commutator, since `c` is even). `ca-ac = κa² -
(-κa)a = κa²+κa² = 2κa² = κ`, using `a²=1/2`. -/
theorem cAB_comm_aAB (n : ℕ) : cAB n * aAB n - aAB n * cAB n = kappaAB n := by
  unfold cAB
  have e0 : aAB n * (kappaAB n * aAB n) = -(kappaAB n * aAB n * aAB n) := by
    rw [show aAB n * (kappaAB n * aAB n) = (aAB n * kappaAB n) * aAB n from by noncomm_ring,
      aAB_mul_kappaAB, neg_mul]
  rw [e0, sub_neg_eq_add]
  have e1 : kappaAB n * aAB n * aAB n + kappaAB n * aAB n * aAB n
      = (2 : ℚ) • (kappaAB n * (aAB n * aAB n)) := by
    rw [two_smul]
    congr 1 <;> noncomm_ring
  rw [e1, aAB_sq, mul_smul_comm, mul_one, smul_smul]
  norm_num

/-- `c = κa` unfolds to the pure tensor `κ ᵍ⊗ₜ aA0 n` (the same computation `A3_independence`
uses for its `e1`). -/
theorem cAB_eq_tmul (n : ℕ) : cAB n = (kappa n) ᵍ⊗ₜ[ℚ] (aA0 n) := by
  unfold cAB kappaAB aAB
  rw [GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (kappa n) (⟨1, SetLike.one_mem_graded (A0Grading n)⟩ : A0Grading n 0)
    (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (aA0 n)]
  rw [mul_one, one_mul]

/-- **X2, third fact**: `[B_u, c] = 0` in `AB n`. Both `B_u ᵍ⊗ₜ 1` and `κ ᵍ⊗ₜ aA0` have the
`W_n`-side factor equal to `1` (resp. arbitrary but purely-even, contributing no sign), so the
graded product picks up no sign in either order, and the two orders agree because `Bu0`/`aA0`
already commute (`a_comm_Bu0`, R2). -/
theorem BuAB_comm_cAB (n : ℕ) (u : Fin (2 * n)) : BuAB n u * cAB n = cAB n * BuAB n u := by
  rw [cAB_eq_tmul]
  unfold BuAB
  rw [GradedTensorProduct.tmul_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
      (1 : RRing n) (⟨Bu0 n u, Bu0_mem_A0Grading_zero n u⟩ : A0Grading n 0)
      (⟨kappa n, kappa_mem_RGradingQ_one n⟩ : RGradingQ n 1) (aA0 n),
    GradedTensorProduct.tmul_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
      (kappa n) (⟨aA0 n, aA0_mem_A0Grading_one n⟩ : A0Grading n 1)
      (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (Bu0 n u)]
  simp only [one_mul, mul_one, mul_zero, uzpow_zero, one_smul]
  rw [a_comm_Bu0]

/-- **X2, `c` is even**: `c = κ ᵍ⊗ₜ aA0` has `κ`'s `R`-degree `1` and `aA0`'s `A_0`-degree `1`,
so `c ∈ ABGrading n (1+1) = ABGrading n 0`. -/
theorem cAB_mem_ABGrading_zero (n : ℕ) : cAB n ∈ ABGrading n 0 := by
  rw [cAB_eq_tmul, show (0 : ZMod 2) = 1 + 1 from by decide]
  exact ABGrading_mem_of_tmul n 1 1 (⟨kappa n, kappa_mem_RGradingQ_one n⟩ : RGradingQ n 1)
    (⟨aA0 n, aA0_mem_A0Grading_one n⟩ : A0Grading n 1)

/-! ## X1 — `eq:source`'s three relations for `b_u := bU n u` -/

theorem betaKappa_mem_RGrading_one (n : ℕ) (u : Fin (2 * n)) :
    betaKappa n u ∈ RGrading n 1 := by
  unfold betaKappa
  have h0 : algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n u) ∈ RGrading n 0 :=
    SetLike.algebraMap_mem_graded _ _
  have h1 := SetLike.mul_mem_graded h0 (kappa_mem_RGrading_one n)
  rwa [zero_add] at h1

theorem betaKappa_mem_RGradingQ_one (n : ℕ) (u : Fin (2 * n)) :
    betaKappa n u ∈ RGradingQ n 1 := betaKappa_mem_RGrading_one n u

theorem aAB_mul_betaKappaAB (n : ℕ) (u : Fin (2 * n)) :
    aAB n * betaKappaAB n u = -(betaKappaAB n u * aAB n) := by
  unfold aAB betaKappaAB
  rw [GradedTensorProduct.tmul_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (1 : RRing n) (⟨aA0 n, aA0_mem_A0Grading_one n⟩ : A0Grading n 1)
    (⟨betaKappa n u, betaKappa_mem_RGradingQ_one n u⟩ : RGradingQ n 1) (1 : A0 n),
    GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (betaKappa n u) (⟨1, SetLike.one_mem_graded (A0Grading n)⟩ : A0Grading n 0)
    (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (aA0 n)]
  simp only [one_mul, mul_one]
  norm_num

theorem BuAB_comm_aAB (n : ℕ) (u : Fin (2 * n)) : BuAB n u * aAB n = aAB n * BuAB n u := by
  unfold BuAB aAB
  rw [GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (1 : RRing n) (⟨Bu0 n u, Bu0_mem_A0Grading_zero n u⟩ : A0Grading n 0)
    (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (aA0 n),
    GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (1 : RRing n) (⟨aA0 n, aA0_mem_A0Grading_one n⟩ : A0Grading n 1)
    (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (Bu0 n u)]
  simp only [mul_one]
  rw [a_comm_Bu0]

/-- **X1, the deformed relation**: `[b_u,a] = β_uκ` — the one relation that would be false for
the unshifted `B_u` alone (`BuAB_comm_aAB` shows `[B_u,a]=0`). Proof mirrors `cAB_comm_aAB`
exactly, with `betaKappaAB n u` in place of `kappaAB n`. -/
theorem bU_comm_aAB (n : ℕ) (u : Fin (2 * n)) :
    bU n u * aAB n - aAB n * bU n u = betaKappaAB n u := by
  have hexp : bU n u * aAB n - aAB n * bU n u
      = (BuAB n u * aAB n - aAB n * BuAB n u)
        + (betaKappaAB n u * aAB n * aAB n - aAB n * (betaKappaAB n u * aAB n)) := by
    unfold bU; noncomm_ring
  rw [hexp, BuAB_comm_aAB, sub_self, zero_add]
  have e0 : aAB n * (betaKappaAB n u * aAB n) = -(betaKappaAB n u * aAB n * aAB n) := by
    rw [show aAB n * (betaKappaAB n u * aAB n) = (aAB n * betaKappaAB n u) * aAB n from by
      noncomm_ring, aAB_mul_betaKappaAB, neg_mul]
  rw [e0, sub_neg_eq_add]
  have e1 : betaKappaAB n u * aAB n * aAB n + betaKappaAB n u * aAB n * aAB n
      = (2 : ℚ) • (betaKappaAB n u * (aAB n * aAB n)) := by
    rw [two_smul]
    congr 1 <;> noncomm_ring
  rw [e1, aAB_sq, mul_smul_comm, mul_one, smul_smul]
  norm_num

/-! ## X1, the undeformed relation `[b_u,b_v]=J_{uv}1` -/

/-- `β_uκ · β_vκ = 0` for all `u,v` — `κ²=0` kills it regardless of the `β`'s, since the
`β`'s (scalars from the commutative base ring `Pn n`) are central. -/
theorem betaKappa_mul_betaKappa (n : ℕ) (u v : Fin (2 * n)) :
    betaKappa n u * betaKappa n v = 0 := by
  unfold betaKappa
  have hcomm : kappa n * algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n v)
      = algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n v) * kappa n :=
    (Algebra.commutes _ _).symm
  calc algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n u) * kappa n *
        (algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n v) * kappa n)
      = algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n u) *
          (kappa n * algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n v)) * kappa n := by
        noncomm_ring
    _ = algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n u) *
          (algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n v) * kappa n) * kappa n := by
        rw [hcomm]
    _ = algebraMap (Indexed.Pn n) (RRing n) (Indexed.betaN n u * Indexed.betaN n v) *
          (kappa n * kappa n) := by rw [map_mul]; noncomm_ring
    _ = 0 := by rw [kappa_sq, mul_zero]

/-- `β_uκ ᵍ⊗ₜ 1 * (1 ᵍ⊗ₜ aA0) = β_uκ ᵍ⊗ₜ aA0` — `betaKappaAB` collapses to a pure tensor once
multiplied by `aAB`, the same computation `cAB_eq_tmul`/`A3_independence`'s `e1` use. -/
theorem betaKappaAB_mul_aAB (n : ℕ) (u : Fin (2 * n)) :
    betaKappaAB n u * aAB n = (betaKappa n u) ᵍ⊗ₜ[ℚ] (aA0 n) := by
  unfold betaKappaAB aAB
  rw [GradedTensorProduct.tmul_coe_mul_zero_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (betaKappa n u) (⟨1, SetLike.one_mem_graded (A0Grading n)⟩ : A0Grading n 0)
    (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (aA0 n)]
  rw [mul_one, one_mul]

/-- `B_u` commutes with any pure tensor `r ᵍ⊗ₜ aA0` with `r` of `R`-degree `1` — the same
computation `BuAB_comm_cAB` uses, generalized: `BuAB`'s `R`-part is always `1` (degree `0`), so
no sign ever appears in either product order (whatever the other factor's degree is), and
`Bu0`/`aA0` commute (`a_comm_Bu0`). -/
theorem BuAB_comm_tmul_aA0 (n : ℕ) (u : Fin (2 * n)) (r : RRing n) (hr : r ∈ RGrading n 1) :
    BuAB n u * (r ᵍ⊗ₜ[ℚ] (aA0 n)) = (r ᵍ⊗ₜ[ℚ] (aA0 n)) * BuAB n u := by
  unfold BuAB
  rw [GradedTensorProduct.tmul_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
      (1 : RRing n) (⟨Bu0 n u, Bu0_mem_A0Grading_zero n u⟩ : A0Grading n 0)
      (⟨r, hr⟩ : RGradingQ n 1) (aA0 n),
    GradedTensorProduct.tmul_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
      r (⟨aA0 n, aA0_mem_A0Grading_one n⟩ : A0Grading n 1)
      (⟨1, SetLike.one_mem_graded (RGradingQ n)⟩ : RGradingQ n 0) (Bu0 n u)]
  simp only [one_mul, mul_one, mul_zero, uzpow_zero, one_smul]
  rw [a_comm_Bu0]

theorem betaKappaAB_mul_betaKappaAB (n : ℕ) (u v : Fin (2 * n)) :
    betaKappaAB n u * betaKappaAB n v = 0 := by
  unfold betaKappaAB
  rw [GradedTensorProduct.tmul_zero_coe_mul_coe_tmul (𝒜 := RGradingQ n) (ℬ := A0Grading n)
    (betaKappa n u) (⟨1, SetLike.one_mem_graded (A0Grading n)⟩ : A0Grading n 0)
    (⟨betaKappa n v, betaKappa_mem_RGradingQ_one n v⟩ : RGradingQ n 1) (1 : A0 n)]
  rw [betaKappa_mul_betaKappa, mul_one]
  simp [GradedTensorProduct.tmul]

/-- **Term D of `[b_u,b_v]`'s expansion**: the two "purely deformation" cross terms cancel. -/
theorem betaKappaAB_mul_aAB_comm (n : ℕ) (u v : Fin (2 * n)) :
    (betaKappaAB n u * aAB n) * (betaKappaAB n v * aAB n)
      - (betaKappaAB n v * aAB n) * (betaKappaAB n u * aAB n) = 0 := by
  have hZY : aAB n * betaKappaAB n v = -(betaKappaAB n v * aAB n) := aAB_mul_betaKappaAB n v
  have hZX : aAB n * betaKappaAB n u = -(betaKappaAB n u * aAB n) := aAB_mul_betaKappaAB n u
  have e1 : betaKappaAB n u * aAB n * (betaKappaAB n v * aAB n)
      = -((betaKappaAB n u * betaKappaAB n v) * (aAB n * aAB n)) := by
    calc betaKappaAB n u * aAB n * (betaKappaAB n v * aAB n)
        = betaKappaAB n u * (aAB n * betaKappaAB n v) * aAB n := by noncomm_ring
      _ = betaKappaAB n u * (-(betaKappaAB n v * aAB n)) * aAB n := by rw [hZY]
      _ = -((betaKappaAB n u * betaKappaAB n v) * (aAB n * aAB n)) := by noncomm_ring
  have e2 : betaKappaAB n v * aAB n * (betaKappaAB n u * aAB n)
      = -((betaKappaAB n v * betaKappaAB n u) * (aAB n * aAB n)) := by
    calc betaKappaAB n v * aAB n * (betaKappaAB n u * aAB n)
        = betaKappaAB n v * (aAB n * betaKappaAB n u) * aAB n := by noncomm_ring
      _ = betaKappaAB n v * (-(betaKappaAB n u * aAB n)) * aAB n := by rw [hZX]
      _ = -((betaKappaAB n v * betaKappaAB n u) * (aAB n * aAB n)) := by noncomm_ring
  rw [e1, e2, betaKappaAB_mul_betaKappaAB, betaKappaAB_mul_betaKappaAB]
  simp

/-- **Term A**: the undeformed commutator, lifted into `AB n`. `BuAB` embeds `B` as a ring
homomorphism (`BuAB_mul`), so the commutator lifts directly through **A1** (`B_comm`). -/
theorem BuAB_comm (n : ℕ) (u v : Fin (2 * n)) :
    BuAB n u * BuAB n v - BuAB n v * BuAB n u = JnQ n u v • (1 : AB n) := by
  have huv : BuAB n u * BuAB n v = (1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n u * Bu0 n v) := BuAB_mul n u v
  have hvu : BuAB n v * BuAB n u = (1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n v * Bu0 n u) := BuAB_mul n v u
  have hsub : ((1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n u * Bu0 n v) : AB n)
        - (1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n v * Bu0 n u)
      = (1 : RRing n) ᵍ⊗ₜ[ℚ] (Bu0 n u * Bu0 n v - Bu0 n v * Bu0 n u) := by
    show (GradedTensorProduct.of ℚ (RGradingQ n) (A0Grading n)
          ((1 : RRing n) ⊗ₜ[ℚ] (Bu0 n u * Bu0 n v)) : AB n)
        - GradedTensorProduct.of ℚ (RGradingQ n) (A0Grading n)
          ((1 : RRing n) ⊗ₜ[ℚ] (Bu0 n v * Bu0 n u))
      = GradedTensorProduct.of ℚ (RGradingQ n) (A0Grading n)
          ((1 : RRing n) ⊗ₜ[ℚ] (Bu0 n u * Bu0 n v - Bu0 n v * Bu0 n u))
    rw [← map_sub, TensorProduct.tmul_sub]
  rw [huv, hvu, hsub]
  have hB : Bu0 n u * Bu0 n v - Bu0 n v * Bu0 n u = JnQ n u v • (1 : A0 n) := by
    unfold Bu0
    rw [show (B n u) ᵍ⊗ₜ[ℚ] (1 : C) * (B n v) ᵍ⊗ₜ[ℚ] (1 : C)
          = (B n u * B n v) ᵍ⊗ₜ[ℚ] (1 : C) from
        GradedTensorProduct.tmul_one_mul_coe_tmul (𝒜 := WGrading n) (ℬ := CGrading)
          (B n u) (⟨B n v, trivial⟩ : WGrading n 0) (1 : C),
      show (B n v) ᵍ⊗ₜ[ℚ] (1 : C) * (B n u) ᵍ⊗ₜ[ℚ] (1 : C)
          = (B n v * B n u) ᵍ⊗ₜ[ℚ] (1 : C) from
        GradedTensorProduct.tmul_one_mul_coe_tmul (𝒜 := WGrading n) (ℬ := CGrading)
          (B n v) (⟨B n u, trivial⟩ : WGrading n 0) (1 : C)]
    have hsub2 : (GradedTensorProduct.of ℚ (WGrading n) CGrading
          ((B n u * B n v : Module.End ℚ (WPoly n)) ⊗ₜ[ℚ] (1 : C)) : A0 n)
        - GradedTensorProduct.of ℚ (WGrading n) CGrading
          ((B n v * B n u : Module.End ℚ (WPoly n)) ⊗ₜ[ℚ] (1 : C))
        = GradedTensorProduct.of ℚ (WGrading n) CGrading
          ((B n u * B n v - B n v * B n u : Module.End ℚ (WPoly n)) ⊗ₜ[ℚ] (1 : C)) := by
      rw [← map_sub, TensorProduct.sub_tmul]
    rw [hsub2, show B n u * B n v - B n v * B n u = opComm (B n u) (B n v) from rfl, B_comm]
    show (GradedTensorProduct.of ℚ (WGrading n) CGrading
        ((JnQ n u v • (1 : Module.End ℚ (WPoly n))) ⊗ₜ[ℚ] (1 : C)) : A0 n)
      = JnQ n u v • (1 : A0 n)
    rw [← TensorProduct.smul_tmul', map_smul, ← Algebra.TensorProduct.one_def,
      GradedTensorProduct.of_one]
  rw [hB]
  show (GradedTensorProduct.of ℚ (RGradingQ n) (A0Grading n)
      ((1 : RRing n) ⊗ₜ[ℚ] (JnQ n u v • (1 : A0 n))) : AB n) = JnQ n u v • (1 : AB n)
  rw [TensorProduct.tmul_smul, map_smul, ← Algebra.TensorProduct.one_def,
    GradedTensorProduct.of_one]

/-! ## X3 — `Φ`, `Ψ`, mutually inverse (route (b)'s concrete rendering)

**Investigated and rejected**: a single inner automorphism `Ad(1+c)` (conjugation by the unit
`1+c`, `c=κa` nilpotent so `1+c` is invertible with inverse `1-c`) does **not** realize the
shift — `BuAB_comm_cAB` shows `B_u` already *commutes* with `c`, so `(1+c)B_u(1-c) = B_u(1-c²) =
B_u` (unchanged), not `B_u+β_uκa`. No other single conjugating element was found that could
realize a *different* shift for each generator `u` (`β_u` varies with `u`) simultaneously as one
inner automorphism, and the manuscript's own proof does not claim one — it verifies the three
relations directly, exactly as X1 does here. Route (b) renders `Φ`/`Ψ`'s "mutually inverse"
content the way the manuscript's own proof actually uses it: the algebraic cancellation that
recovers each generator from the other. -/

theorem bU_sub_eq_BuAB (n : ℕ) (u : Fin (2 * n)) :
    bU n u - betaKappaAB n u * aAB n = BuAB n u := by
  unfold bU; abel

theorem BuAB_add_eq_bU (n : ℕ) (u : Fin (2 * n)) :
    BuAB n u + betaKappaAB n u * aAB n = bU n u := rfl

/-- **Terms B, C**: `B_u`/`B_v` each commute with the *other's* deformation term. -/
theorem BuAB_comm_betaKappaAB_mul_aAB (n : ℕ) (u v : Fin (2 * n)) :
    BuAB n u * (betaKappaAB n v * aAB n) = (betaKappaAB n v * aAB n) * BuAB n u := by
  rw [betaKappaAB_mul_aAB]
  exact BuAB_comm_tmul_aA0 n u (betaKappa n v) (betaKappa_mem_RGrading_one n v)

/-- **X1, the undeformed relation, assembled**: `[b_u,b_v] = J_{uv}1` — `Jn` from the frozen
`Indexed.lean` appearing literally (via `JnQ`, exactly as A1 quoted it). All three deformation
cross-terms (`Term B`, `Term C`, `Term D`) cancel; only the lifted undeformed commutator
(`Term A`, A1) survives. -/
theorem bU_comm_bU (n : ℕ) (u v : Fin (2 * n)) :
    bU n u * bU n v - bU n v * bU n u = JnQ n u v • (1 : AB n) := by
  have hexp : bU n u * bU n v - bU n v * bU n u
      = (BuAB n u * BuAB n v - BuAB n v * BuAB n u)
        + (BuAB n u * (betaKappaAB n v * aAB n) - (betaKappaAB n v * aAB n) * BuAB n u)
        + ((betaKappaAB n u * aAB n) * BuAB n v - BuAB n v * (betaKappaAB n u * aAB n))
        + ((betaKappaAB n u * aAB n) * (betaKappaAB n v * aAB n)
            - (betaKappaAB n v * aAB n) * (betaKappaAB n u * aAB n)) := by
    unfold bU; noncomm_ring
  rw [hexp, BuAB_comm, BuAB_comm_betaKappaAB_mul_aAB, sub_self,
    show (betaKappaAB n u * aAB n) * BuAB n v - BuAB n v * (betaKappaAB n u * aAB n) = 0 from by
      rw [BuAB_comm_betaKappaAB_mul_aAB n v u, sub_self],
    betaKappaAB_mul_aAB_comm]
  abel

end Source
end InhomogeneousDeformations
